---
### EPEL repo

- name: Ensure epel repo present
  yum:
    name: epel-release
    state: present

- name: Enable epel repo
  shell: yum-config-manager --enable epel

- name: Ensure common packages present
  yum:
    name: nginx
    state: present

- name: Copy content of the web site
  copy:
    src: website/
    dest: /usr/share/nginx/html/
  become: yes

- name: Start nginx
  service:
    name: nginx
    state: started
  become: yes


